import {
  Add,
  Ai,
  AiGenerate,
  Analytics,
  Apps,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowsHorizontal,
  Asleep,
  Attachment,
  Building,
  Calculator,
  Calendar,
  CaretDown,
  Category,
  CenterSquare,
  ChartBar,
  ChartLine,
  ChartPie,
  ChartStacked,
  Checkmark,
  CheckmarkOutline,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Close,
  ColorPalette,
  Copy,
  CreateLink,
  Currency,
  CurrencyDollar,
  Dashboard,
  Document,
  DocumentAttachment,
  DocumentPdf,
  Download,
  Draggable,
  Edit,
  Email,
  Equalizer,
  ErrorOutline,
  FaceActivated,
  Filter,
  Finance,
  Flash,
  Folder,
  FolderDetails,
  Globe,
  Grid,
  Information,
  InventoryManagement,
  Launch,
  Light,
  Link,
  List,
  ListBulleted,
  ListChecked,
  Menu,
  MisuseOutline,
  NoImage,
  Notification,
  OverflowMenuHorizontal,
  OverflowMenuVertical,
  Package,
  Pdf,
  PlayFilled,
  PlayOutline,
  QrCode,
  Receipt,
  RecentlyViewed,
  Renew,
  Repeat,
  Ruler,
  Search,
  Send,
  SendAlt,
  SettingsAdjust,
  Share,
  SortAscending,
  Star,
  StopFilled,
  StopOutline,
  Subdirectory,
  Subtract,
  Tag,
  Task,
  ThumbsDown,
  ThumbsDownFilled,
  ThumbsUp,
  ThumbsUpFilled,
  Ticket,
  Time,
  TriangleOutline,
  UserAvatar,
  View,
  VolumeMute,
  VolumeUp,
  WarningAlt,
  Waveform,
  Zip,
} from '@carbon/icons-react';

export const Icons = {
  AccountCircle: UserAvatar,
  Add,
  Ai,
  AiGenerate,
  Analytics,
  Apps,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowsHorizontal,
  Asleep,
  Attachment,
  Block: MisuseOutline,
  Bolt: Flash,
  Building,
  Calculator,
  Calendar,
  CaretDown,
  Category,
  CenterSquare,
  ChartBar,
  ChartLine,
  ChartPie,
  ChartStacked,
  Check: Checkmark,
  CheckCircle: CheckmarkOutline,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Close,
  Copy,
  CreateLink,
  Currency,
  CurrencyDollar,
  Dashboard,
  Document,
  DocumentAttachment,
  DocumentPdf,
  Download,
  Draggable,
  Edit,
  Email,
  Equalizer,
  Error: ErrorOutline,
  ExpandLess: ChevronUp,
  ExpandMore: ChevronDown,
  ExternalLink: Launch,
  FaceActivated,
  Filter,
  Finance,
  Folder,
  FolderDetails,
  Globe,
  Grid,
  History: RecentlyViewed,
  Info: Information,
  Inventory: InventoryManagement,
  Light,
  Link,
  List,
  ListBulleted,
  ListChecked,
  Menu,
  MoreHoriz: OverflowMenuHorizontal,
  MoreVertical: OverflowMenuVertical,
  NoImage,
  Notification,
  Package,
  Palette: ColorPalette,
  Pdf,
  Play: PlayFilled,
  PlayOutline,
  QrCode,
  Receipt,
  Refresh: Renew,
  Remove: Subtract,
  Repeat,
  Ruler,
  Search,
  Send,
  SendAlt,
  Share,
  Sort: SortAscending,
  Star,
  Stop: StopFilled,
  StopOutline,
  Subdirectory,
  Tag,
  Task,
  ThumbsDown,
  ThumbsDownFilled,
  ThumbsUp,
  ThumbsUpFilled,
  Ticket,
  Time,
  Triangle: TriangleOutline,
  Tune: SettingsAdjust,
  View,
  VolumeMute,
  VolumeUp,
  Warning: WarningAlt,
  Waveform,
  Zip,
};

export type IconName = keyof typeof Icons;

export const carbonIconNames = {
  AccountCircle: 'UserAvatar',
  Add: 'Add',
  Ai: 'Ai',
  AiGenerate: 'AiGenerate',
  Analytics: 'Analytics',
  Apps: 'Apps',
  ArrowDown: 'ArrowDown',
  ArrowDownRight: 'ArrowDownRight',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ArrowUp: 'ArrowUp',
  ArrowUpRight: 'ArrowUpRight',
  ArrowsHorizontal: 'ArrowsHorizontal',
  Asleep: 'Asleep',
  Attachment: 'Attachment',
  Block: 'MisuseOutline',
  Bolt: 'Flash',
  Building: 'Building',
  Calculator: 'Calculator',
  Calendar: 'Calendar',
  CaretDown: 'CaretDown',
  Category: 'Category',
  CenterSquare: 'CenterSquare',
  ChartBar: 'ChartBar',
  ChartLine: 'ChartLine',
  ChartPie: 'ChartPie',
  ChartStacked: 'ChartStacked',
  Check: 'Checkmark',
  CheckCircle: 'CheckmarkOutline',
  ChevronDown: 'ChevronDown',
  ChevronLeft: 'ChevronLeft',
  ChevronRight: 'ChevronRight',
  ChevronUp: 'ChevronUp',
  Close: 'Close',
  Copy: 'Copy',
  CreateLink: 'CreateLink',
  Currency: 'Currency',
  CurrencyDollar: 'CurrencyDollar',
  Dashboard: 'Dashboard',
  Document: 'Document',
  DocumentAttachment: 'DocumentAttachment',
  DocumentPdf: 'DocumentPdf',
  Download: 'Download',
  Draggable: 'Draggable',
  Edit: 'Edit',
  Email: 'Email',
  Equalizer: 'Equalizer',
  Error: 'ErrorOutline',
  ExpandLess: 'ChevronUp',
  ExpandMore: 'ChevronDown',
  ExternalLink: 'Launch',
  FaceActivated: 'FaceActivated',
  Filter: 'Filter',
  Finance: 'Finance',
  Folder: 'Folder',
  FolderDetails: 'FolderDetails',
  Globe: 'Globe',
  Grid: 'Grid',
  History: 'RecentlyViewed',
  Info: 'Information',
  Inventory: 'InventoryManagement',
  Light: 'Light',
  Link: 'Link',
  List: 'List',
  ListBulleted: 'ListBulleted',
  ListChecked: 'ListChecked',
  Menu: 'Menu',
  MoreHoriz: 'OverflowMenuHorizontal',
  MoreVertical: 'OverflowMenuVertical',
  NoImage: 'NoImage',
  Notification: 'Notification',
  Package: 'Package',
  Palette: 'ColorPalette',
  Pdf: 'Pdf',
  Play: 'PlayFilled',
  PlayOutline: 'PlayOutline',
  QrCode: 'QrCode',
  Receipt: 'Receipt',
  Refresh: 'Renew',
  Remove: 'Subtract',
  Repeat: 'Repeat',
  Ruler: 'Ruler',
  Search: 'Search',
  Send: 'Send',
  SendAlt: 'SendAlt',
  Share: 'Share',
  Sort: 'SortAscending',
  Star: 'Star',
  Stop: 'StopFilled',
  StopOutline: 'StopOutline',
  Subdirectory: 'Subdirectory',
  Tag: 'Tag',
  Task: 'Task',
  ThumbsDown: 'ThumbsDown',
  ThumbsDownFilled: 'ThumbsDownFilled',
  ThumbsUp: 'ThumbsUp',
  ThumbsUpFilled: 'ThumbsUpFilled',
  Ticket: 'Ticket',
  Time: 'Time',
  Triangle: 'TriangleOutline',
  Tune: 'SettingsAdjust',
  View: 'View',
  VolumeMute: 'VolumeMute',
  VolumeUp: 'VolumeUp',
  Warning: 'WarningAlt',
  Waveform: 'Waveform',
  Zip: 'Zip',
} as const satisfies Record<IconName, string>;
