import {
  MdArrowBack,
  MdArrowDownward,
  MdArrowDropDown,
  MdArrowForward,
  MdArrowRightAlt,
  MdArrowUpward,
  MdAttachMoney,
  MdAutoAwesome,
  MdBolt,
  MdChangeHistory,
  MdCheck,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdDescription,
  MdDownloading,
  MdDragIndicator,
  MdErrorOutline,
  MdExpandLess,
  MdExpandMore,
  MdFolder,
  MdFolderZip,
  MdInventory2,
  MdIosShare,
  MdMenu,
  MdMoreHoriz,
  MdOutlineAccountBalance,
  MdOutlineAccountCircle,
  MdOutlineAdd,
  MdOutlineAddLink,
  MdOutlineArrowOutward,
  MdOutlineAssuredWorkload,
  MdOutlineAttachEmail,
  MdOutlineAttachFile,
  MdOutlineAttachMoney,
  MdOutlineAutoAwesome,
  MdOutlineBlock,
  MdOutlineBrokenImage,
  MdOutlineCalculate,
  MdOutlineCalendarMonth,
  MdOutlineCategory,
  MdOutlineCheckCircle,
  MdOutlineClear,
  MdOutlineConfirmationNumber,
  MdOutlineContentCopy,
  MdOutlineCropFree,
  MdOutlineDarkMode,
  MdOutlineDashboardCustomize,
  MdOutlineEditNote,
  MdOutlineEmail,
  MdOutlineEqualizer,
  MdOutlineFace,
  MdOutlineFactCheck,
  MdOutlineFilterList,
  MdOutlineForwardToInbox,
  MdOutlineGraphicEq,
  MdOutlineGridView,
  MdOutlineHistory,
  MdOutlineInfo,
  MdOutlineInsights,
  MdOutlineInventory2,
  MdOutlineLanguage,
  MdOutlineLaunch,
  MdOutlineLeaderboard,
  MdOutlineLightMode,
  MdOutlineLink,
  MdOutlineListAlt,
  MdOutlineMoreTime,
  MdOutlineMoreVert,
  MdOutlineNotificationsNone,
  MdOutlineOpenInNew,
  MdOutlinePalette,
  MdOutlinePictureAsPdf,
  MdOutlinePieChart,
  MdOutlinePlayArrow,
  MdOutlineQrCode2,
  MdOutlineReceiptLong,
  MdOutlineRefresh,
  MdOutlineReorder,
  MdOutlineRepeat,
  MdOutlineShowChart,
  MdOutlineSignpost,
  MdOutlineSquareFoot,
  MdOutlineStackedBarChart,
  MdOutlineStar,
  MdOutlineStop,
  MdOutlineStyle,
  MdOutlineSubdirectoryArrowLeft,
  MdOutlineSyncAlt,
  MdOutlineTask,
  MdOutlineThumbDown,
  MdOutlineThumbUp,
  MdOutlineTune,
  MdOutlineVisibility,
  MdOutlineVolumeOff,
  MdOutlineVolumeUp,
  MdOutlineWarning,
  MdOutlineWidgets,
  MdPictureAsPdf,
  MdPlayArrow,
  MdRefresh,
  MdRemove,
  MdSearch,
  MdSnippetFolder,
  MdSort,
  MdStop,
  MdTrendingDown,
  MdTrendingUp,
} from 'react-icons/md';

export const Icons = {
  Overview: MdOutlineWidgets,
  Close: MdClose,
  PdfOutline: MdOutlinePictureAsPdf,
  Amount: MdOutlineEqualizer,
  Attachments: MdOutlineAttachFile,
  Refresh: MdRefresh,
  Currency: MdAttachMoney,
  Inventory2: MdInventory2,
  Notifications: MdOutlineNotificationsNone,
  ChevronDown: MdExpandMore,
  ChevronUp: MdExpandLess,
  TrendingUp: MdTrendingUp,
  TrendingDown: MdTrendingDown,
  Category: MdOutlineCategory,
  Visibility: MdOutlineVisibility,
  Face: MdOutlineFace,
  MoreHoriz: MdMoreHoriz,
  Pdf: MdPictureAsPdf,
  BrokenImage: MdOutlineBrokenImage,
  Description: MdDescription,
  FolderZip: MdFolderZip,
  ChevronRight: MdChevronRight,
  ChevronLeft: MdChevronLeft,
  ArrowBack: MdArrowBack,
  ArrowForward: MdArrowForward,
  Folder: MdFolder,
  Search: MdSearch,
  Error: MdErrorOutline,
  AI: MdAutoAwesome,
  AIOutline: MdOutlineAutoAwesome,
  Insights: MdOutlineInsights,
  Time: MdOutlineMoreTime,
  Add: MdOutlineAdd,
  Copy: MdOutlineContentCopy,
  Share: MdIosShare,
  Play: MdPlayArrow,
  Stop: MdStop,
  StopOutline: MdOutlineStop,
  PlayOutline: MdOutlinePlayArrow,
  MoreVertical: MdOutlineMoreVert,
  Match: MdOutlineTask,
  History: MdOutlineHistory,
  Email: MdOutlineEmail,
  Tune: MdOutlineTune,
  Change: MdChangeHistory,
  CalendarMonth: MdOutlineCalendarMonth,
  Sort: MdSort,
  Palette: MdOutlinePalette,
  Menu: MdMenu,
  Mute: MdOutlineVolumeOff,
  UnMute: MdOutlineVolumeUp,
  Clear: MdOutlineClear,
  Filter: MdOutlineFilterList,
  Status: MdOutlineStyle,
  Accounts: MdOutlineAccountBalance,
  ArrowRightAlt: MdArrowRightAlt,
  AccountCircle: MdOutlineAccountCircle,
  Repeat: MdOutlineRepeat,
  ProjectStatus: MdDownloading,
  Edit: MdOutlineEditNote,
  OpenInNew: MdOutlineOpenInNew,
  DragIndicator: MdDragIndicator,
  ExternalLink: MdOutlineLaunch,
  Link: MdOutlineLink,
  AddLink: MdOutlineAddLink,
  CropFree: MdOutlineCropFree,
  DateFormat: MdOutlineFactCheck,
  Tax: MdOutlineAssuredWorkload,
  Vat: MdOutlineCalculate,
  CurrencyOutline: MdOutlineAttachMoney,
  SnippetFolder: MdSnippetFolder,
  ConfirmationNumber: MdOutlineConfirmationNumber,
  QrCode: MdOutlineQrCode2,
  ArrowOutward: MdOutlineArrowOutward,
  Straighten: MdOutlineSquareFoot,
  Files: MdOutlineInventory2,
  GridView: MdOutlineGridView,
  ListView: MdOutlineReorder,
  ArrowDownward: MdArrowDownward,
  ArrowUpward: MdArrowUpward,
  SubdirectoryArrowLeft: MdOutlineSubdirectoryArrowLeft,
  OutgoingMail: MdOutlineSignpost,
  AttachEmail: MdOutlineAttachEmail,
  ForwardToInbox: MdOutlineForwardToInbox,
  SyncAlt: MdOutlineSyncAlt,
  InfoOutline: MdOutlineInfo,
  DashboardCustomize: MdOutlineDashboardCustomize,
  ThumbUp: MdOutlineThumbUp,
  ThumbDown: MdOutlineThumbDown,
  ThumbUpOutline: MdOutlineThumbUp,
  ThumbDownOutline: MdOutlineThumbDown,
  RefreshOutline: MdOutlineRefresh,
  Globle: MdOutlineLanguage,
  Record: MdOutlineGraphicEq,
  Speed: MdOutlineStackedBarChart,
  ReceiptLong: MdOutlineReceiptLong,
  Bolt: MdBolt,
  Star: MdOutlineStar,
  ShowChart: MdOutlineShowChart,
  Leaderboard: MdOutlineLeaderboard,
  PieChart: MdOutlinePieChart,
  ArrowDropDown: MdArrowDropDown,
  Block: MdOutlineBlock,
  ListAlt: MdOutlineListAlt,
  LightMode: MdOutlineLightMode,
  DarkMode: MdOutlineDarkMode,
  Check: MdCheck,
  Remove: MdRemove,
  Info: MdOutlineInfo,
  Warning: MdOutlineWarning,
  CheckCircle: MdOutlineCheckCircle,
  ExpandLess: MdExpandLess,
  ExpandMore: MdExpandMore,
};

export type IconName = keyof typeof Icons;
